version: '3.7'
services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
        - "3306:3306"
    volumes:
        - fastapi_ecommerce:/data/db
  # ecommerce-fastapi:
    # build: .
    # env_file:
      # - .env
    # ports:
      # - "8000:8000"
    # depends_on:
        # db:
          # condition: service_healthy

volumes:
  fastapi_ecommerce: